### ISSUE TITLE
ReadMe outdated

### ISSUE THREAD

**Issue by jeijkenboom** [pcmind/degiro-java-client#1]
It seems the readme is outdated?
DeGiro::getPortfolioSummary does not exist any more, for example

**Comment by pcmind** [comment]
You are correct. I'll update the documentation.

This method has been removed in the favor of using update all (like is been done by the Degiro portal itself):
 `  DUpdates updateAll(long lastOrderUpdate, long lastPortfolioUpdate, long lastPortfolioSummaryUpdate, long lastHistoricalOrders, long lastTransactions, long lastAlerts) throws DeGiroException ;`

I'm thinking about making it a bit more flexible to get only part of update stream but need to give it some thought. Any idea is welcome.
