### ISSUE TITLE
Unexpected API Response because firstLoginWizardUrl is null

### ISSUE THREAD

**Issue by clijsters** [pcmind/degiro-java-client#3]
When trying to invoke an API method, the validation vor `DConfig` throws a DValidationException, because `firstLoginWizardUrl` is null. If I understand it correctly, this url is not mandatory.

So imo [line 43 in DConfig.java](https://github.com/pcmind/degiro-java-client/blob/master/src/main/java/cat/indiketa/degiro/model/DConfig.java#L42) should be removed to fix that error.

Are there any plans on using validation annotations? This would allow to easily declare mandatory and nullable fields.

Exception:

    cat.indiketa.degiro.exceptions.DValidationException: Unexpected API Response: DResponse(status=200, url=https://trader.degiro.nl/login/secure/config, method=GET, text={"data":{"tradingUrl":"https://trader.degiro.nl/trading/secure/","paUrl":"https://trader.degiro.nl/pa/secure/","reportingUrl":"https://trader.degiro.nl/reporting/secure/","paymentServiceUrl":"https://trader.degiro.nl/payments/","productSearchUrl":"https://trader.degiro.nl/product_search/secure/","dictionaryUrl":"https://trader.degiro.nl/product_search/config/dictionary/","productTypesUrl":"https://trader.degiro.nl/product_search/config/productTypes/","companiesServiceUrl":"https://trader.degiro.nl/dgtbxdsservice/","i18nUrl":"https://trader.degiro.nl/i18n/","vwdQuotecastServiceUrl":"https://trader.degiro.nl/vwd-quotecast-service/","vwdNewsUrl":"https://solutions.vwdservices.com/customers/degiro.nl/news-feed/api/","vwdGossipsUrl":"https://solutions.vwdservices.com/customers/degiro.nl/news-feed/api/","taskManagerUrl":"https://trader.degiro.nl/taskmanager/","refinitivNewsUrl":"https://trader.degiro.nl/dgtbxdsservice/newsfeed/v2","refinitivAgendaUrl":"https://trader.degiro.nl/dgtbxdsservice/agenda/v2","refinitivCompanyProfileUrl":"https://trader.degiro.nl/dgtbxdsservice/company-profile/v2","refinitivCompanyRatiosUrl":"https://trader.degiro.nl/dgtbxdsservice/company-ratios","refinitivFinancialStatementsUrl":"https://trader.degiro.nl/dgtbxdsservice/financial-statements","landingPath":"/trader/","betaLandingPath":"/beta-trader/","mobileLandingPath":"/trader/","loginUrl":"https://trader.degiro.nl/login/de","sessionId":"00000.00000","clientId":00000}})
	at cat.indiketa.degiro.DeGiroImpl.requestAndValidate(DeGiroImpl.java:242)
	at cat.indiketa.degiro.DeGiroImpl.httpGet(DeGiroImpl.java:224)
	at cat.indiketa.degiro.DeGiroImpl.login(DeGiroImpl.java:202)
	at cat.indiketa.degiro.DeGiroImpl.ensureLogged(DeGiroImpl.java:181)
	at cat.indiketa.degiro.DeGiroImpl.getAccountOverview(DeGiroImpl.java:136)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cat.indiketa.degiro.session.DSessionExpiredRetryProxy.invoke(DSessionExpiredRetryProxy.java:34)
	at com.sun.proxy.$Proxy91.getAccountOverview(Unknown Source)

**Comment by pcmind** [comment]
You are correct, I have seen this last time I use my app, but didn't push the change. I'll fix it.
Regarding validation annotations, I am open to any improvement PR. If I have time I'll look into it.
