### ISSUE TITLE
QuoteCastUrl has changed

### ISSUE THREAD

**Issue by guspav** [pcmind/degiro-java-client#4]
Hi,

The quote cast url has changed by Degiro from "https://degiro.quotecast.vwdservices.com/CORS/" to "https://trader.degiro.nl/vwd-quotecast-service/" as result the function newVwdSession() does not work anymore. It returns "404 - File or directory not found. The resource you are looking for might have been removed, had his name changed, or is temporary unavailable."
Regards

**Comment by pcmind** [comment]
Thank you for reporting.
Yes the URL has changed but the workflow to get VwdSession has also changed; so we'll need to investigate API changes. 
You can verify this with a modified instance of DeGiroHost.

**Comment by Chavithra** [comment]
Hello there,

I have both good and a bad news for you.

**Good news**
This endpoint works with the same workflow on my side :
https://degiro.quotecast.vwdservices.com/CORS/

**Bad news**
This probably means the bug is in the library or the way the test was made.

Hope that will help

**Comment by pcmind** [comment]
It seam that you are correct; endpoint is still the one been used, but header validation hare more restrictive and with incorrect header we get Error code 401.
I'll fix the issue.

**Comment by guspav** [comment]
It is still does not work for me... With endpoint "https://trader.degiro.nl/vwd-quotecast-service/" it returns the following html instead of json
![image](https://user-images.githubusercontent.com/76010238/105901243-5fa68a00-601d-11eb-85d8-ba0effdaeb65.png)

**Comment by pcmind** [comment]
Strange. I have a Portuguese account and have no problem with current endpoint. The web app is still using the "https://degiro.quotecast.vwdservices.com/CORS/". Did you try to change the endpoint providing the modified URL?

**Comment by guspav** [comment]
Hi, I've modified my previous post. The error message come with new price update end point. The old one ("https://degiro.quotecast.vwdservices.com/CORS/") finally works for me. My fault.
Thanks a lot for your support. How did you back engineered the API? Just looking Degiro site? If, for example, one day they will change version string is there an easy way to discover it value?

**Comment by pcmind** [comment]
You are welcome. 
I usually use browser debug console and Filddler2 and them do some trial an error. The full API may change at any time and it is not that evident to detect what changed.  Like in this case; not much changed but the server was more restrictive accepted headers.
